"""add user model

Revision ID: e91d2ec2ef03
Revises: b29cf3d685d9
Create Date: 2025-06-10 13:19:28.439268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91d2ec2ef03'
down_revision: Union[str, None] = 'b29cf3d685d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Posts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Posts', 'Users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Posts', type_='foreignkey')
    op.drop_column('Posts', 'user_id')
    op.drop_table('Users')
    # ### end Alembic commands ###
